# Project Properties
group=com.noahblclarkson.autotune
version=2.0.0-SNAPSHOT

# Dependency Versions
paperVersion=1.21.4-R0.1-SNAPSHOT
cloudCoreVersion=2.0.0
cloudPaperVersion=2.0.0-beta.14
guiceVersion=7.0.0
hikariVersion=7.0.2
jdbiVersion=3.51.0
sqliteVersion=3.51.1.0
mariadbVersion=3.5.7
javalinVersion=6.7.0
gsonVersion=2.13.2
inventoryFrameworkVersion=0.11.6
# Gradle Settings
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
