'use client';

import { useWizard } from './wizard-context';
import { wizardArchetypes, type ServerType, type PlayerCount, type GoalKey } from '@/lib/wizard-data';
import { useState } from 'react';
import { Download, ExternalLink, MessageCircle, Check } from 'lucide-react';

function generateYaml(
  serverType: ServerType,
  playerCount: PlayerCount,
  goals: GoalKey[],
): string {
  const defaults = wizardArchetypes.defaults;
  const serverData = wizardArchetypes.serverTypes[serverType];
  const playerData = wizardArchetypes.playerCounts[playerCount];

  const spread = Math.round((serverData.spread + playerData.spreadDelta) * 100) / 100;
  const maxPriceChange = Math.round((defaults.maxPriceChangePercent + playerData.spreadDelta * 2) * 100) / 100;
  const clampedSpread = Math.max(0.10, Math.min(0.40, spread));

  // Collect goal-based additions
  const floorPercent = goals.includes('seller_protection') ? 60 : 0;
  const treasuryTax = goals.includes('treasury') ? 0.03 : defaults.treasury.taxRate;
  const lowDebt = goals.includes('low_debt');
  const funVolatility = goals.includes('fun_volatility');

  const finalMaxPriceChange = funVolatility ? 2.5 : maxPriceChange;

  // Build YAML
  const lines: string[] = [
    '# Auto-Tune Config — Generated by Setup Wizard',
    `# Server type: ${serverData.name} | Players: ${playerData.name} | Goals: ${goals.length > 0 ? goals.join(', ') : 'none'}`,
    '',
    'economy:',
    `  baseSpread: ${clampedSpread.toFixed(2)}      # Starting spread (0.15=tight, 0.30=wide)`,
  ];

  if (floorPercent > 0) {
    lines.push('  spread:');
    lines.push(`    floor-percent: ${floorPercent}     # Floor: items cannot drop below ${floorPercent}% of base price`);
  }

  if (funVolatility) {
    lines.push(`  max-price-change-percent: ${finalMaxPriceChange.toFixed(1)}   # Higher = faster price discovery`);
  }

  lines.push('');

  // Player archetypes section
  if (serverData.archetype) {
    const { MarketMaker: mmCount, GuildBuyer: gbCount, GuildBuyerThreshold: gbThreshold } = serverData.archetype;
    lines.push('player-archetypes:');
    lines.push('  MarketMaker:');
    lines.push(`    count: ${mmCount}              # Number of market maker agents`);
    lines.push('  GuildBuyer:');
    lines.push(`    count: ${gbCount}              # Number of guild buyer agents`);
    lines.push(`    threshold: ${gbThreshold}           # % below target price to start buying`);
    lines.push('');
  }

  // Loans section
  const loansSection: string[] = ['loans:'];
  loansSection.push(`  counter-cyclical: true   # Reduce interest as debt/GDP rises`);
  if (lowDebt) {
    loansSection.push(`  credit-score-multiplier: 1.5   # Stricter loan approval`);
    loansSection.push(`  post-default-cooldown-hours: 336   # 14 days (low debt mode)`);
  } else {
    loansSection.push(`  credit-score-multiplier: 1.0   # Default`);
    loansSection.push(`  post-default-cooldown-hours: 168   # 7 days`);
  }
  if (serverData.loans?.tier3Ratio) {
    loansSection.push(`  tier3-ratio: ${serverData.loans.tier3Ratio}             # Circuit breaker threshold`);
  }
  lines.push(...loansSection);
  lines.push('');

  // Treasury section
  const treasurySection: string[] = ['treasury:'];
  treasurySection.push(`  tax-rate: ${treasuryTax}          # ${Math.round(treasuryTax * 100)}% tax on all transactions`);
  lines.push(...treasurySection);
  lines.push('');

  lines.push('# ─────────────────────────────────────────────────────');
  lines.push('# NOTE: Review all values before deploying to production.');
  lines.push('# Full config reference: https://github.com/noahbclarkson/Auto-Tune/blob/rewrite-2/docs/CONFIG_GUIDE.md');
  lines.push('# ─────────────────────────────────────────────────────');

  return lines.join('\n');
}

function downloadYaml(yaml: string, filename: string) {
  const blob = new Blob([yaml], { type: 'text/yaml;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ConfigExport() {
  const { state } = useWizard();
  const { serverType, playerCount, goals } = state.answers;
  const [copied, setCopied] = useState(false);

  if (!serverType || !playerCount) return null;

  const yaml = generateYaml(serverType, playerCount as PlayerCount, goals as GoalKey[]);

  const handleCopy = () => {
    navigator.clipboard.writeText(yaml).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleDownload = () => {
    downloadYaml(yaml, 'autotune-config.yml');
  };

  return (
    <div>
      <div className="text-center mb-6">
        <h2 className="text-xl font-bold text-white mb-2">Your config is ready</h2>
        <p className="text-gray-400 text-sm">
          Copy or download the generated config, then paste it into your server's <code className="text-emerald-400 bg-gray-800 px-1.5 py-0.5 rounded text-xs">config.yml</code>.
        </p>
      </div>

      {/* YAML display */}
      <div className="max-w-3xl mx-auto mb-6">
        <div className="flex items-center justify-between mb-2">
          <span className="text-xs text-gray-500 font-mono">config.yml</span>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium text-gray-300 hover:text-white hover:bg-gray-800 transition-colors"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : null}
              {copied ? 'Copied!' : 'Copy'}
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium text-gray-300 hover:text-white hover:bg-gray-800 transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              Download
            </button>
          </div>
        </div>
        <pre className="bg-gray-950 border border-gray-800 rounded-xl p-4 text-xs text-gray-300 font-mono overflow-x-auto leading-relaxed">
          {yaml}
        </pre>
      </div>

      {/* Actions */}
      <div className="flex flex-col sm:flex-row items-center justify-center gap-3 max-w-xl mx-auto">
        <a
          href="/simulator"
          className="flex items-center gap-2 px-5 py-2.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-medium text-sm transition-colors w-full sm:w-auto justify-center"
        >
          <ExternalLink className="w-4 h-4" />
          Open in Simulator
        </a>
        <a
          href="https://discord.gg/autotune"
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-2 px-5 py-2.5 rounded-lg border border-gray-700 hover:border-gray-600 text-gray-300 hover:text-white font-medium text-sm transition-colors w-full sm:w-auto justify-center"
        >
          <MessageCircle className="w-4 h-4" />
          Need help? Join Discord
        </a>
      </div>

      <p className="text-center text-gray-600 text-xs mt-6">
        {wizardArchetypes.serverTypes[serverType as ServerType]?.name ?? serverType} · {playerCount} players · {goals.length > 0 ? `${goals.length} goal(s) selected` : 'no goals'}
      </p>
    </div>
  );
}
